/*________________________________________________________________F_KEYS____*/
#define  		  F1_KEY       		 0x3b00
#define 		  F2_KEY       		 0x3c00
#define  		  F3_KEY       		 0x3d00
#define    		F4_KEY       		 0x3e00
#define    		F5_KEY       		 0x3f00
#define    		F6_KEY       		 0x4000
#define    		F7_KEY       		 0x4100
#define    		F8_KEY       		 0x4200
#define    		F9_KEY       		 0x4300
#define    		F10_KEY      		 0x4400
/*___________________________________________________________CTRL_F_KEYS____*/
#define    		CTRL_F1      		 0x5e00
#define    		CTRL_F2      		 0x5f00
#define    		CTRL_F3      		 0x6000
#define    		CTRL_F4      		 0x6100
#define    		CTRL_F5      		 0x6200
#define    		CTRL_F6      		 0x6300
#define    		CTRL_F7      		 0x6400
#define    		CTRL_F8      		 0x6500
#define    		CTRL_F9      		 0x6600
#define    		CTRL_F10     		 0x6700
/*____________________________________________________________ALT_F_KEYS____*/
#define    		ALT_F1       		 0x6800
#define    		ALT_F2       		 0x6900
#define    		ALT_F3       		 0x6a00
#define    		ALT_F4       		 0x6b00
#define    		ALT_F5           0x6c00
#define    		ALT_F6           0x6d00
#define    		ALT_F7           0x6e00
#define    		ALT_F8           0x6f00
#define    		ALT_F9           0x7000
#define    		ALT_F10          0x7100
/*__________________________________________________________SHIFT_F_KEYS____*/
#define    		SHIFT_F1     		 0x5400
#define    		SHIFT_F2     		 0x5500
#define    		SHIFT_F3     		 0x5600
#define    		SHIFT_F4     		 0x5700
#define    		SHIFT_F5     		 0x5800
#define    		SHIFT_F6     		 0x5900
#define    		SHIFT_F7     		 0x5a00
#define    		SHIFT_F8     		 0x5b00
#define    		SHIFT_F9     		 0x5c00
#define    		SHIFT_F10    		 0x5d00
/*__________________________________________________________________KEYS____*/
#define       Q_KEY            0x1071
#define       W_KEY            0x1177
#define       E_KEY            0x1265
#define       R_KEY            0x1372
#define       T_KEY            0x1474
#define       Y_KEY            0x1579
#define       U_KEY            0x1675
#define       I_KEY            0x1769
#define       O_KEY            0x186f
#define       P_KEY            0x1970
#define       A_KEY            0x1e61
#define       S_KEY            0x1f73
#define       D_KEY            0x2064
#define       F_KEY            0x2166
#define       G_KEY            0x2267
#define       H_KEY            0x2368
#define       J_KEY            0x246a
#define       K_KEY            0x256b
#define       L_KEY            0x266c
#define       Z_KEY            0x2c7a
#define       X_KEY            0x2d78
#define       C_KEY            0x2e63
#define       V_KEY            0x2f76
#define       B_KEY            0x3062
#define       N_KEY            0x316e
#define       M_KEY            0x326d
/*__________________________________________________________CONTROL_KEYS____*/
#define       CTRL_S           0x1f13
#define       CTRL_D           0x2004
#define       CTRL_F           0x2106
#define       CTRL_G           0x2207
#define       CTRL_H           0x2308
#define       CTRL_J           0x240a
#define       CTRL_K           0x250b
#define       CTRL_L           0x260c
/*______________________________________________________________ALT_KEYS____*/
#define    		ALT_E        		 0x1200
#define    		ALT_R        		 0x1300
#define    		ALT_I        		 0x1700
#define    		ALT_O        		 0x1800
#define    		ALT_H        		 0x2300
#define    		ALT_K        		 0x2500
#define    		ALT_X        		 0x2d00
#define    		ALT_C        		 0x2e00
/*____________________________________________________________SHIFT_KEYS____*/
#define       SHIFT_Y          0x1559
#define       SHIFT_N          0x314e
/*__________________________________________________________________________*/
#define    		ESCKEY       		 0x011b
#define    		BSKEY        		 0x0e08
#define    		TABKEY       		 0x0f09
#define    		CRKEY        		 0x1c0d
#define    		HOMEKEY      		 0x4700
#define    		UPKEY        		 0x4800
#define    		PGUPKEY      		 0x4900
#define    		GREY_MINUS     	 0x4a2d
#define    		LEFTKEY      		 0x4b00
#define    		GREY_PLUS      	 0x4e2b
#define    		RIGHTKEY     		 0x4d00
#define    		ENDKEY       		 0x4f00
#define    		DOWNKEY      		 0x5000
#define    		PGDNKEY      		 0x5100
#define    		INSKEY       		 0x5200
#define    		DELKEY       		 0x5300
/*__________________________________________________________________________*/
#define    		CTRL_BRK         0x0000                              /* Break */
#define    		CTRL_PRT         0x7200                       /* Print Screen */
#define    		CTRL_LEFT        0x7300 
#define    		CTRL_RIGHT       0x7400 
#define    		CTRL_END         0x7500 
#define    		CTRL_PGDN        0x7600 
#define    		CTRL_HOME        0x7700 
#define    		CTRL_PGUP        0x8400 
#define    		CTRL_CR          0x1c0a 
#define    		CTRL_BS          0x0e7f 
/*__________________________________________________________________________*/
#define    		SHIFT_UP         0x4838 
#define    		SHIFT_DOWN       0x5032 
#define    		SHIFT_LEFT       0x4b34 
#define    		SHIFT_RIGHT      0x4d36 
#define    		SHIFT_HOME       0x4737 
#define    		SHIFT_END        0x4f31 
#define    		SHIFT_PGUP       0x4939 
#define    		SHIFT_PGDN       0x5133 
#define    		SHIFT_DEL        0x532e 
/*__________________________________________________________________________*/
